platform :ios, 7.0
pod 'AFNetworking'
pod 'Reachability'
pod 'SVProgressHUD' 
pod 'RDVTabBarController'
pod 'KGModal'
pod 'SDWebImage'
pod 'ShareKit/Core'
pod 'ShareKit/Twitter'
pod 'ShareKit/Facebook'
pod 'ShareKit/GooglePlus'
